// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function GetDatabaseHealth():Promise<main.DatabaseHealth>;

export function GetImportStatistics():Promise<main.ImportStatistics>;

export function GetRecentImports(arg1:number):Promise<Array<models.SalesRecord>>;

export function Greet(arg1:string):Promise<string>;

export function ImportHTMLData(arg1:string):Promise<main.ImportResult>;

export function ImportHTMLDataBatch(arg1:string):Promise<main.ImportResult>;

export function ImportHTMLDataWithOptions(arg1:string,arg2:main.ImportOptions):Promise<main.ImportResult>;

export function ValidateHTMLData(arg1:string):Promise<main.ValidationResult>;
