// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDatabaseHealth() {
  return window['go']['main']['App']['GetDatabaseHealth']();
}

export function GetImportStatistics() {
  return window['go']['main']['App']['GetImportStatistics']();
}

export function GetRecentImports(arg1) {
  return window['go']['main']['App']['GetRecentImports'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportHTMLData(arg1) {
  return window['go']['main']['App']['ImportHTMLData'](arg1);
}

export function ImportHTMLDataBatch(arg1) {
  return window['go']['main']['App']['ImportHTMLDataBatch'](arg1);
}

export function ImportHTMLDataWithOptions(arg1, arg2) {
  return window['go']['main']['App']['ImportHTMLDataWithOptions'](arg1, arg2);
}

export function ValidateHTMLData(arg1) {
  return window['go']['main']['App']['ValidateHTMLData'](arg1);
}
